### ISSUE TITLE
Question: Preventing sheet from closing when interacting with elements (Android)

### ISSUE THREAD

**Issue by szheleshchenko** [lodev09/react-native-true-sheet#141]
Hey, I ran into an issue on Android where the sheet closes when interacting with elements inside it (like a `DatePicker`, but could be any interactive element). On iOS, the sheet stays open when using

```
<View
  onStartShouldSetResponder={() => true}
  onResponderTerminationRequest={() => false}
/>
```

but on Android, these props don't work.

I tried to workaround it with adding a `ScrollView` and passing `scrollRef` to the sheet, but that was no use.

Is there a way to prevent this behavior on Android without disabling the sheet's movement altogether? It's a pretty common use case to have interactive elements inside the bottom sheet that shouldn’t trigger a close action when touched.

Would love some help or suggestions on how to handle this. Thanks! 🙌

**Comment by lodev09** [comment]
Hey @szheleshchenko, do you have a reproducible example?

**Comment by szheleshchenko** [comment]
@lodev09 Yes, I created an example using DatePicker. https://github.com/szheleshchenko/true-sheet-reproduction/blob/master/app/index.tsx

Here's how it looks:
<details open><summary>Details</summary>

https://github.com/user-attachments/assets/baf615a5-0d3c-420d-bc6c-2af7541d9584

</details>

**Comment by skaionedev** [comment]
Any updates or solutions to fix this issue on android?

**Comment by szheleshchenko** [comment]
> Any updates or solutions to fix this issue on android?

I use react-native-actions-sheet for this particular case. This library is practically unusable on iOS and has poor performance, but as a temporary solution for Android, it's fine.

**Comment by lodev09** [comment]
@skaionedev your issue just needs `flexGrow` style on the `GestureHandlerRootView` wrapper.

@szheleshchenko should be fixed in PR #156 along with other android touch issues.

> This library is practically unusable on iOS and has poor performance

Can you open a separate issue regarding this? Thanks

**Comment by szheleshchenko** [comment]
@lodev09 Sorry for the confusion. By 'this library,' I meant `react-native-actions-sheet`. Everything is fine with true-sheet on iOS. 🙂

**Comment by lodev09** [comment]
@szheleshchenko ohh I see. no worries. Can you checkout fix in #156 please? :)

**Comment by skaionedev** [comment]
@lodev09  `flexGrow` helps to enable dragging on Android but it doesn't solve my problem that I have with dragging top item to bottom  (bottom-sheet closes and prevents list from reordering) 
https://github.com/omahili/react-native-reorderable-list/issues/35#issuecomment-2687198012

**Comment by lodev09** [comment]
@skaionedev okay, fix should be in PR #156

**Comment by skaionedev** [comment]
> [@lodev09](https://github.com/lodev09) `flexGrow` helps to enable dragging on Android but it doesn't solve my problem that I have with dragging top item to bottom (bottom-sheet closes and prevents list from reordering) [omahili/react-native-reorderable-list#35 (comment)](https://github.com/omahili/react-native-reorderable-list/issues/35#issuecomment-2687198012)

@lodev09  I'm still experiencing same issue

**Comment by lodev09** [comment]
@skaionedev open a new issue and provide e repro. thanks!
