### ISSUE TITLE
[bug][ios]: sheet breaks detach of modals on reload (pressing R)

### ISSUE THREAD

**Issue by hirbod** [lodev09/react-native-true-sheet#34]
It seems like the sheet prevents modals and transparentModals from being detached correctly on a hard reload (R button), making the app unresponsive and forcing me to reboot the app many times during development. While this is not a huge deal since it does not affect production, it is super annoying in development when you work on sheets and have some reloads or hot refreshes that mount and unmount the transparent modal behind.

It works fine for modals if the sheet is not open, but as soon as the sheet is open, the modal is not detaching. See the two videos (red background added to my stack to demonstrate the problem).

| No sheet, app responsive after reboot | With sheet not responsive anymore|
|--------|--------|
| <video width="320" height="240" controls src="https://github.com/lodev09/react-native-true-sheet/assets/504909/0413dd3c-7e03-4dba-a4de-5194835c0df7"></video> | <video width="320" height="240" controls src="https://github.com/lodev09/react-native-true-sheet/assets/504909/d87a995f-af62-4f4d-a286-21452655677b"></video> |

Also, I tested the same behavior with multiple modals stacked on top of eachother. It works flawlessly, the problem only occurs with true sheet being open.
Kindly appreciate a fix here.

**Comment by lodev09** [comment]
Yeah, I'm not sure if there's a proper fix for that since it's how IOS handles viewcontrollers internally.

I think what's happening is that the Modal gets destroyed first leaving TrueSheet in the air. It's the same issue with RN navigation modals as well.

I tried finding a way to fix it before but couldn't find one. It's a deep rabbit hole when working with stacked modal view controllers.

Sorry.

**Comment by hirbod** [comment]
It is not happening with RN navigation modals, thats what I tried to showcase. The video with only red (without the sheet) gets removed, but when I have a modal, that opened the sheet, it does not work anymore.

**Comment by lodev09** [comment]
Okay.. I guess I got confused :D. So, sheet gets removed first and then RN modal did not get the chance to detach. Again, this is a known issue and I'm suffering from it as well even with react-nativation/native. It's something to do with hot reloading + modals.

I wonder if it can be fixed here:
https://github.com/lodev09/react-native-true-sheet/blob/d30b873544e4b02b0478304555f326f6d44eabce/ios/TrueSheetView.swift#L161-L163

Try to disable animation on that line.

**Comment by lodev09** [comment]
Just curious, what's your reason in using RN modal? I assume it's the red one.

**Comment by hirbod** [comment]
I'll try to disable the animation to see if that fixes it. The main reason we're using the `transparentModal` is as I explained here https://github.com/lodev09/react-native-true-sheet/discussions/32. We're using react-navigation.

**Comment by hirbod** [comment]
> Again, this is a known issue and I'm suffering from it as well even with react-nativation/native
This is not true. I opened two transparentModal on top of each other without using your library, and reloading successfully detaches them. If one of those modals contains your sheet, it breaks.

Summoning the debug king @intergalacticspacehighway

**Comment by hirbod** [comment]
I was able to patch the issue in [RNSScreenStack.mm](https://github.com/software-mansion/react-native-screens/blob/main/ios/RNSScreenStack.mm)

```obj-c
// updated this
- (void)invalidate {
    _invalidated = YES;
    [self dismissAllPresentedViewControllersFrom:_controller completion:^{
        // Ensure presented modals are removed and the controller is detached from its parent
        [_presentedModals removeAllObjects];
        [_controller willMoveToParentViewController:nil];
        [_controller removeFromParentViewController];
    }];
}

- (void)dismissOnReload {
    dispatch_async(dispatch_get_main_queue(), ^{
        [self invalidate];
    });
}

// added this
- (void)dismissAllPresentedViewControllersFrom:(UIViewController *)viewController completion:(void (^)(void))completion {
    if (viewController.presentedViewController) {
        [viewController.presentedViewController dismissViewControllerAnimated:NO completion:^{
            [self dismissAllPresentedViewControllersFrom:viewController completion:completion];
        }];
    } else {
        completion();
    }
}
```


https://github.com/lodev09/react-native-true-sheet/assets/504909/191470af-e9b5-4526-9170-5fce0c6c1e21

**Comment by hirbod** [comment]
Fix is here https://github.com/software-mansion/react-native-screens/pull/2175

**Comment by lodev09** [comment]
OMG thank you for fixing rn screens 😂

I'm actually traveling so I couldn't help much. I'll take a look at implementing the same fix on the sheet since it could also be an issue with stacked sheet.

**Comment by lodev09** [comment]
> The main reason we're using the transparentModal is as I explained here https://github.com/lodev09/react-native-true-sheet/discussions/32. We're using react-navigation.

I see. An alternative solution I would suggest is capture `route.params` with the screen instead of implementing a transparent modal. See [here](https://github.com/lodev09/react-native-true-sheet/issues/28#issuecomment-2136743664)

```ts
useEffect(() => {
  ;(async () =>  {
    if (id) {
      await sheet.current?.present()
      navigation.setParams({ id: undefined })
    }
  })()
}, [id])
```

**Comment by hirbod** [comment]
We rely on many lifecycle/focus/blur events; this approach wouldn’t work. Furthermore, your suggestion would require mounting all of the views in the root. Our sheets can be accessed from everywhere and are mounted “lazily” thanks to our implementation, and no extra code needed.

**Comment by lodev09** [comment]
Ah that makes sense. Definitely not good solution if you have lots of sheets that accepts links.

Good luck.

**Comment by hirbod** [comment]
Well everything works fine now with the patch :). Once we get your PR merged it's hopefully mounting a bit faster

**Comment by lodev09** [comment]
yep. The PR works for IOS but I'm seeing layout issues with android when orientation changes. I won't be able to fix them until I get back home in few days. However, I would appreciate if you could test it more and I can merge it when I get a chance then create separate PR for the layout issue :)

**Comment by hirbod** [comment]
Sounds good, if you consider it ready for testing I could give it a shot. Orientation change isn't an issue for us but maybe for others, but sounds good to address separately.

**Comment by wcastand** [comment]
i'm not sure it's related but on expo when i press R, my ios app crashes with this error

```TrueSheet/TrueSheetView.swift:140: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value```

hope that can help, not sure if it's only a reload/dev thing or not tho yet

![Screenshot 2024-06-09 at 14 34 46](https://github.com/lodev09/react-native-true-sheet/assets/2178244/22a9325e-eb53-4116-ad61-e5b497515c28)

**Comment by hirbod** [comment]
Not related to this issue, but what Expo version are you using?

**Comment by wcastand** [comment]
using : 
- "expo": "^51.0.11",
- "@lodev09/react-native-true-sheet": "^0.11.3",

**Comment by wcastand** [comment]
not 100% but almost everytime yeah, in my repo i had a scenario where i would get it 100%, but when i dev, it's not all the time.

i have a TrueSheet in my input component so it's present in a lot of screen so yeah, happens a lot. 

nice for the Pr i will test as soon as it's possible then

**Comment by hirbod** [comment]
I guess you have a case that triggers a width change, thus the event is fired for you.
The PR should fix this effectively.

**Comment by lodev09** [comment]
@hirbod  PR looks good with minor comments.

Closing this. Thank you!

**Comment by hirbod** [comment]
@lodev09 just an FYI that my PR was merged but they slightly changed the implementation logic: https://github.com/software-mansion/react-native-screens/pull/2175

My PR made sure to close all modals recursively, including third party modals but they decided to limit this to RNS, which kinda makes sense but likely won't work as smooth as my initial idea. So we should try and test. Maybe we need appropriate destroy methods that close on dealloc within your library. Just as a little heads up.

**Comment by rranjan14** [comment]
I am using version 2.0.6 with expo@53. Still crashing on ios. I have created a repo where I am able to repro it. https://github.com/rranjan14/bottom-sheet-crash-repro
